### ISSUE TITLE
Create a Julia package

### ISSUE THREAD

**Issue by ericagol** [ericagol/NbodyGradient.jl#1]
- [x] Add a license.
- [x] Add .gitignore
- [x] Add code to call package.
- [x] Automate tests.
- [x] #73
- [x] Develop Jupyter notebooks to give examples.

**Comment by giordano** [comment]
Creating a package with `PkgDev.generate()` actually does some of the outlined points for you (adding the requested license, creating a standard `.gitignore`, creating the file `test/runtests.jl`).  However, it's not hard to do that manually.  

The default content of the `.gitignore` is
```
*.jl.cov
*.jl.*.cov
*.jl.mem
```
Unless you need something specific for this project, the above configuration should be sufficient.

**Comment by langfzac** [comment]
PR #36 Adds (or updates) these.

> * [x]  Add .gitignore
> * [x]  Add code to call package.
> * [x]  Automate tests.

**Comment by langfzac** [comment]
Closing this and moving talks of documentation to #73
