### ISSUE TITLE
Updates needed to code

### ISSUE THREAD

**Issue by ericagol** [ericagol/NbodyGradient.jl#18]
- [ ] Need to add `phic!` to `dh17!` and `ah18!` with `dqdt` computed.
- [ ] Need to add setting `jac_step` to identity matrix before calling `phisalpha` when `alpha != 0`

**Comment by ericagol** [comment]
- [ ] Need to add descriptions of the `dq/dt` computation used in `findtransit3` to the paper.
- [ ] Also add compensated summation to `findtransit3`.
- [ ] Need to add & test `dq/dt` in `kepler_driftij` and `ah18` so that it can be used in `findtransit3` (which is currently using `dh17`).  This was tricky to do, so I need to go back and look at the notes.

**Comment by ericagol** [comment]
- [ ] Add a test for `phic`.

**Comment by langfzac** [comment]
This issue is out of date. No longer using dh17, and updates have been added to the new integrator.
