### ISSUE TITLE
Missing transit when stepsize is large

### ISSUE THREAD

**Issue by ericagol** [ericagol/NbodyGradient.jl#20]
I found that integrating the following system:

`1.0,0.0,0.0,0.0,0.0,0.0,0.0
3.e-5,1.51234829,1.038398,0.02436651768325364,0.018169884000968452,1.5707963267948966,3.141592653589793
3.e-5,2.42148938,1.868189,0.020060810686211832,0.011189705094395375,1.5707963267948966,3.141592653589793`

with `h=0.07`, `t0=3000`, `tmax = 200`, that the first transit is missed for step sizes of `h` and `h/2`, but then it is found for `h/4`, `h/8`, `h/16`.

Not sure what to do about this...

**Comment by langfzac** [comment]
Just ran this in the latest version -- no longer an issue.
