### ISSUE TITLE
Compatibility with new version of NbodyGradient

### ISSUE THREAD

**Issue by ericagol** [ericagol/NbodyGradient.jl#35]
@langfzac   Is this Jupyter notebook consistent with your newest version of NbodyGradient?

https://github.com/ericagol/NbodyGradient/blob/master/examples/ttv_example.ipynb

**Comment by langfzac** [comment]
No, but the one I just pushed to my fork is.  [https://github.com/langfzac/NbodyGradient/blob/master/examples/ttv_example.ipynb](https://github.com/langfzac/NbodyGradient/blob/master/examples/ttv_example.ipynb)

**Comment by bmlindor** [comment]
Just a quick Q, How does this compare with the compensated_summation branch?

**Comment by ericagol** [comment]
@bmlindor  I believe that branch has been merged with the master branch in the main repository.  @langfzac has been developing some new code to interface with the integrator, including structures to hold the variables, new ways to initiate the initial conditions, and integration of more general hiearchies.  This version he is developing on his fork of this repository.

**Comment by langfzac** [comment]
Notebook updated in #36
