### ISSUE TITLE
Speeding up computation of sinh(x) and cosh(x)

### ISSUE THREAD

**Issue by ericagol** [ericagol/NbodyGradient.jl#37]
- [ ] Try the following:  expmx=exp(-x);y=expmx*expm1(2x)/2; z=(expmx+inv(expmx))/2
where y=sinh(x) and z=cosh(x).  This gives about a 25% savings in computing these in v1.5.2.

**Comment by giordano** [comment]
Note that in Julia v1.6 `sinh` and `cosh` are much faster: https://github.com/JuliaLang/julia/pull/37426

Julia v1.5:
```julia
julia> using BenchmarkTools

julia> @btime y .= sinh.(x) setup = (x = randn(1000); y = similar(x));
  22.414 μs (0 allocations: 0 bytes)

julia> @btime y .= cosh.(x) setup = (x = randn(1000); y = similar(x));
  15.094 μs (0 allocations: 0 bytes)
```

Julia v1.6:
```julia
julia> using BenchmarkTools

julia> @btime y .= sinh.(x) setup = (x = randn(1000); y = similar(x));
  8.082 μs (0 allocations: 0 bytes)

julia> @btime y .= cosh.(x) setup = (x = randn(1000); y = similar(x));
  6.833 μs (0 allocations: 0 bytes)
```

**Comment by ericagol** [comment]
Thanks, @giordano !  It looks like these are ~twice as fast as the expressions I've written above; nice!  Do you know if there is a function like `sincos(x)`, but hyperbolic which computes `sinh(x)` and `cosh(x)` simultaneously (with time savings)?

**Comment by giordano** [comment]
Hehe, I also looked for it.  There doesn't seem to be a `sincosh`, but that'd probably a good addition.  Mind [opening an issue](https://github.com/JuliaLang/julia/issues/new)?

**Comment by ericagol** [comment]
Leaving this for now.
