### ISSUE TITLE
Add paper to the repository

### ISSUE THREAD

**Issue by ericagol** [ericagol/NbodyGradient.jl#48]
- [x] Transfer the paper from Overleaf to GitHub.
- [ ] Allow CI to (re-)create figures & paper.

**Comment by langfzac** [comment]
The paper is now in [langfzac/nbg-papers](https://github.com/langfzac/nbg-papers). I'm moving the second bullet point to a new issue there: [#3](https://github.com/langfzac/nbg-papers/issues/3).
