### ISSUE TITLE
Rename repo to NbodyGradient.jl

### ISSUE THREAD

**Issue by langfzac** [ericagol/NbodyGradient.jl#55]
Should rename to keep with Julia conventions.

Also, we could add to the package registry: https://github.com/JuliaRegistries/Registrator.jl/#registrator

**Comment by ericagol** [comment]
@langfzac  I have a repository with the name NbodyGradient.jl.  Can you remind me what happened with that?

**Comment by langfzac** [comment]
@ericagol I think that was the first attempt at packaging the code. We ended up making too many changes to this repo, so I just decided to start over by forking this one. It should be fine to archive or delete entirely.

**Comment by ericagol** [comment]
Okay, I've deleted.  I'm happy for you to rename this repo.

**Comment by langfzac** [comment]
Hmm, I can still navigate to ericagol/NbodyGradient.jl. Are you sure it's been deleted? I just removed my fork.

**Comment by ericagol** [comment]
Oh, sorry, I just deleted it locally.   

Eric

**Comment by ericagol** [comment]
@langfzac Okay, I changed it to https://github.com/ericagol/NbodyGradient_legacy.jl

We can delete later!

I'll change NbodyGradient -> NbodyGradient.jl

**Comment by ericagol** [comment]
Okay, done!
