### ISSUE TITLE
Bug when calling dh17! with BigFloat jacobian

### ISSUE THREAD

**Issue by ericagol** [ericagol/NbodyGradient.jl#7]
test_dh17.jl has a commented out section in which it calls dh17! with BigFloat precision to compute the Jacobian.  The returned jacobian has an error in which each data point is off by a factor of order unity;  it looks like there is a problem with the passing of a BigFloat array to the subroutine and modifying it within.  This was solved by adding an output to dh17!, but in general this isn't a workable solution.

**Comment by ericagol** [comment]
I just ran into this problem again!

**Comment by langfzac** [comment]
We no longer use dh17. Closing this
